#!/bin/bash

echo "🎯 Android Studio专项调试方案"
echo "============================="

echo ""
echo "✅ 模拟器状态检查："
if adb devices | grep -q "device"; then
    echo "✓ 模拟器已连接"
    adb devices
else
    echo "❌ 模拟器未连接，正在启动..."
    $ANDROID_HOME/emulator/emulator -avd Pixel_6_Pro_API_26 &
    echo "请等待15秒模拟器启动..."
fi

echo ""
echo "🚀 启动Android Studio进行调试："
echo "1. 执行: open -a 'Android Studio' ."
echo "2. 等待项目同步"
echo "3. 开始调试"

# 启动Android Studio
open -a "Android Studio" .

echo ""
echo "📋 调试检查清单："
echo ""
echo "【基本配置检查】"
echo "✓ 项目结构：22个Kotlin文件已确认"
echo "✓ 配置文件：gradle.properties已修复"
echo "✓ 依赖库：25个库已配置"
echo "✓ 模拟器：已连接"

echo ""
echo "【在Android Studio中的调试步骤】"
echo ""
echo "🔧 1. 项目同步"
echo "   - 等待'Gradle sync'完成"
echo "   - 如有错误，查看'Build'窗口"

echo ""
echo "🎯 2. 设置断点建议"
echo "   关键调试点："
echo "   ├── app/src/main/java/com/mpcwallet/app/MPCWalletApplication.kt:40"
echo "   │   (应用初始化)"
echo "   ├── app/src/main/java/com/mpcwallet/app/ui/MainActivity.kt:25"
echo "   │   (主Activity创建)"
echo "   ├── app/src/main/java/com/mpcwallet/app/crypto/MPCKeyGenerator.kt:50"
echo "   │   (密钥生成入口)"
echo "   ├── app/src/main/java/com/mpcwallet/app/utils/QRCodeManager.kt:30"
echo "   │   (QR码生成)"
echo "   └── app/src/main/java/com/mpcwallet/app/network/EthereumService.kt:45"
echo "       (网络服务初始化)"

echo ""
echo "🐞 3. 启动调试"
echo "   - 选择设备: emulator-5554"
echo "   - 点击Debug按钮 (🐞)"
echo "   - 或使用快捷键: Shift+F9"

echo ""
echo "📊 4. 调试窗口说明"
echo "   ├── Variables: 查看变量值"
echo "   ├── Watches: 监控表达式"
echo "   ├── Call Stack: 调用栈信息"
echo "   ├── Logcat: 应用日志"
echo "   └── Console: 调试输出"

echo ""
echo "🔍 5. MPC功能专项调试"
echo ""
echo "   【密钥生成调试】"
echo "   - 在MPCKeyGenerator.generateKeyShares()设置断点"
echo "   - 检查threshold和n值"
echo "   - 验证keyShares数组长度"
echo "   - 观察SecureRandom生成过程"
echo ""
echo "   【签名过程调试】"
echo "   - 在MPCSigner.signTransaction()设置断点"
echo "   - 检查privateKeyShares参数"
echo "   - 验证部分签名生成"
echo "   - 观察签名聚合过程"
echo ""
echo "   【QR码通信调试】"
echo "   - 在QRCodeManager.generateQRCode()设置断点"
echo "   - 检查数据序列化"
echo "   - 验证QR码内容"
echo "   - 测试数据分片逻辑"

echo ""
echo "📱 6. 应用功能测试路径"
echo "   测试流程："
echo "   1. 启动应用 → MainActivity"
echo "   2. 查看钱包列表 → WalletScreen"
echo "   3. 创建新钱包 → KeyGenerationScreen"
echo "   4. 设置阈值参数 → MPC密钥生成"
echo "   5. 生成QR码 → QRCodeManager"
echo "   6. 扫描QR码 → QRScanScreen"
echo "   7. 发送交易 → TransactionScreen"

echo ""
echo "🔧 7. 故障排除"
echo "   常见问题解决："
echo "   - Gradle同步失败: 检查网络连接"
echo "   - 构建错误: 查看Build输出"
echo "   - 运行时异常: 查看Logcat日志"
echo "   - MPC算法错误: 检查BouncyCastle初始化"

echo ""
echo "📋 8. 日志监控命令"
echo "   在终端运行以下命令监控日志："
echo "   adb logcat | grep -E '(MPCWallet|MPC_|Error|Exception)'"

echo ""
echo "🎉 调试环境已准备就绪！"
echo "现在可以在Android Studio中开始调试了。" 