#!/bin/bash

echo "🐛 MPC钱包应用调试完整指南"
echo "==============================="

echo ""
echo "📱 当前设备状态："
adb devices

echo ""
echo "🔧 调试方法选择："
echo "1. Android Studio可视化调试 (推荐)"
echo "2. 命令行调试"
echo "3. 日志监控调试"
echo "4. MPC功能专项调试"

echo ""
echo "=== 方法1: Android Studio调试 ==="
echo "1. 启动Android Studio: open -a 'Android Studio' ."
echo "2. 等待项目同步完成"
echo "3. 设置断点位置："
echo "   - MainActivity.onCreate() - 应用启动"
echo "   - MPCKeyGenerator.generateKeyShares() - 密钥生成"
echo "   - MPCSigner.signTransaction() - 交易签名"
echo "   - QRCodeManager.generateQRCode() - QR码生成"
echo "4. 点击 Debug 'app' (🐞) 按钮"
echo "5. 在Variables窗口查看变量值"
echo "6. 在Logcat查看应用日志"

echo ""
echo "=== 方法2: 命令行调试 ==="
echo "构建Debug版本："
echo "./gradlew assembleDebug"
echo ""
echo "安装到设备："
echo "./gradlew installDebug"
echo ""
echo "启动应用："
echo "adb shell am start -n com.mpcwallet.app/.ui.MainActivity"

echo ""
echo "=== 方法3: 日志监控 ==="
echo "实时查看应用日志："
echo "adb logcat | grep MPCWallet"
echo ""
echo "过滤特定标签："
echo "adb logcat -s \"MPC_DEBUG\""
echo ""
echo "保存日志到文件："
echo "adb logcat > debug_log.txt"

echo ""
echo "=== 方法4: MPC功能调试要点 ==="
echo "🔐 密钥生成调试："
echo "- 检查Shamir分片数量和阈值"
echo "- 验证密钥分片的随机性"
echo "- 确认分片重构的正确性"
echo ""
echo "🔒 签名过程调试："
echo "- 验证部分签名的生成"
echo "- 检查签名聚合算法"
echo "- 确认最终签名的有效性"
echo ""
echo "📲 QR码通信调试："
echo "- 检查QR码数据完整性"
echo "- 验证数据分片和重组"
echo "- 测试设备间通信协议"

echo ""
echo "🚨 常见调试场景："
echo ""
echo "【场景1: 应用无法启动】"
echo "1. 检查权限配置: cat app/src/main/AndroidManifest.xml | grep uses-permission"
echo "2. 查看启动日志: adb logcat | grep -E '(FATAL|ERROR)'"
echo "3. 验证依赖库: ./gradlew dependencies"
echo ""
echo "【场景2: MPC功能异常】"
echo "1. 检查BouncyCastle初始化"
echo "2. 验证密钥分片存储"
echo "3. 测试加密解密功能"
echo ""
echo "【场景3: 网络连接问题】"
echo "1. 检查Infura API密钥配置"
echo "2. 验证网络权限"
echo "3. 测试区块链连接" 