#!/bin/bash

echo "🔧 修复 Android Studio Run Configuration"
echo "====================================="

echo ""
echo "❌ 错误: Module not specified"
echo "📋 解决方案: 重新创建Run Configuration"

echo ""
echo "🎯 在 Android Studio 中执行以下步骤:"

echo ""
echo "【方法1: 自动创建Run Configuration】"
echo "1. 确保项目已完全同步"
echo "2. 点击工具栏上的 'Add Configuration...'"
echo "3. 或点击 Run/Debug 按钮旁的下拉菜单"
echo "4. 选择 'Edit Configurations...'"

echo ""
echo "【方法2: 手动创建Run Configuration】"
echo "===================================="
echo ""
echo "步骤 1: 打开配置界面"
echo "   Run > Edit Configurations..."
echo ""
echo "步骤 2: 删除现有的错误配置"
echo "   - 选择任何现有的 'app' 配置"
echo "   - 点击 '-' 按钮删除"
echo ""
echo "步骤 3: 创建新的Android App配置"
echo "   - 点击 '+' 按钮"
echo "   - 选择 'Android App'"
echo ""
echo "步骤 4: 配置参数"
echo "   Name: app"
echo "   Module: MPCWallet.app (从下拉列表中选择)"
echo "   Package: com.mpcwallet.app"
echo "   Activity: .ui.MainActivity"
echo ""
echo "步骤 5: 应用配置"
echo "   - 点击 'Apply'"
echo "   - 点击 'OK'"

echo ""
echo "【方法3: 项目重新同步】"
echo "===================="
echo "如果模块下拉列表是空的:"
echo ""
echo "1. File > Sync Project with Gradle Files"
echo "2. 等待同步完成"
echo "3. File > Invalidate Caches and Restart"
echo "4. 选择 'Invalidate and Restart'"
echo "5. 重新创建Run Configuration"

echo ""
echo "【验证模块可见性】"
echo "==============="
echo "检查模块是否正确识别:"
echo ""
echo "1. File > Project Structure"
echo "2. 左侧选择 'Modules'"
echo "3. 应该看到:"
echo "   - MPCWallet (项目根模块)"
echo "   - MPCWallet.app (应用模块)"
echo ""
echo "如果看不到 MPCWallet.app:"
echo "4. 点击 '+' > Import Gradle Project"
echo "5. 选择 app 目录"
echo "6. 导入为 Gradle 模块"

echo ""
echo "📱 检查设备连接"
adb devices

echo ""
echo "🔍 调试信息"
echo "==========="
echo "当前项目结构:"
echo "├── settings.gradle (已修复)"
if grep -q "include ':app'" settings.gradle; then
    echo "│   ✓ include ':app' 已添加"
else
    echo "│   ❌ include ':app' 缺失"
fi
echo "├── build.gradle (项目级)"
echo "└── app/"
echo "    └── build.gradle (模块级)"

echo ""
echo "⚡ 快速修复命令"
echo "============="
echo ""
echo "如果Android Studio无响应，可以:"
echo "1. 完全关闭Android Studio"
echo "2. 删除项目缓存:"
echo "   rm -rf .idea/"
echo "   rm -rf .gradle/"
echo "3. 重新打开项目"

echo ""
echo "🚀 启动Android Studio"
open -a "Android Studio" .

echo ""
echo "✅ 修复步骤完成!"
echo ""
echo "💡 关键提示:"
echo "- 确保在Module字段选择 'MPCWallet.app'"
echo "- 如果下拉列表为空，先执行Gradle同步"
echo "- 必要时重启Android Studio" 